### ISSUE TITLE
Cannot set property 'user' of undefined

### ISSUE THREAD

**Issue by ConeyIsland** [ozon1234/passport-odnoklassniki#6]
Привет, какие-то баги стали вылазить после обновления на последнюю версию паспорта (0.3.0 вроде бы). Судя по всему сломалось у всех.

Аналогичные ошибки с другими авторизациями:
https://github.com/jaredhanson/passport/issues/400
http://stackoverflow.com/questions/32187787/passport-js-github-strategy-callback-always-returns-typeerror-cannot-set-prope

С одноклассниками та же ошибка. Причём что самое страшное - ломает эта фича любую авторизацию на сайте!

Временное решение, прописать конкретную версию паспорта в конфиге и не обновляться.

**Comment by atomoc** [comment]
https://github.com/ozon1234/passport-odnoklassniki/pull/7
